### ISSUE TITLE
Layout is not saved for some applications

### ISSUE THREAD

**Issue by ANtlord** [ramok/xxkb#2] opened 2022-05-18 20:05 UTC
Hello!

First of all I realize that the repository is not the original repository.  I know that the original project is located on sourceforge. But this project seems more alive.

Here is the thing. I've found that layout doesn't work for some applications.  In fact, I experience the issue with Vivaldi browser, Evince and Geary.  xxkb takes into account those windows which pass its filter in function `ExpectInput`.  It fetches the WM_HINTS via `XGetWMHints`  and WM_PROTOCOLS via `XGetWMProtocols`.  According the manual of xlib both of the properties are not mandatory.  So windows are able to handle focus events without setting the properties.

I'm thinking about removing the filter at all, but it doesn't seem a right solution.  I was wondering if you have any idea about the issue.

**Comment by ramok** [comment] 2022-05-18 22:31
> First of all I realize that the repository is not the original repository. I know that the original project is located on sourceforge. But this project seems more alive.

Yeah, this  is a reason why I create this repo - to collect all changes what come after xxkb not maintained anymore :(

That interesting. I test it on evince and on geary. When it focus after starting - xxkb did't work. When I switch focus on other window and switch it back to evince or geary - xxkb works. Can you verify it?

**Comment by ramok** [comment] 2022-05-18 22:52
Some update: described by me behavior  is true for xmonad.
I try reproduce in fluxbox, and everything works..

What WM you use? Looks like it depends from WM

**Comment by ANtlord** [comment] 2022-05-19 08:06
I'm using i3. It appears that it was too late so I was wrong about evince and geary, layout switching work just fine with them. But the issue still occurs with vivaldi browser.

**Comment by ANtlord** [comment] 2022-09-21 20:35
Ok, I've found where is the problem.  Your fork works just fine!  The result of the call `XQueryTree(dpy, temp_win, &rwin, &parent, &children, &num);` wasn't checked in the origin.  As a consequence `XFree(children);` was called with an uninitialized pointer.

Solved

**Comment by ANtlord** [comment] 2022-09-24 22:02
I'm sorry.  I thought that had opened an issue about crashing.  I've found some application which don't work as well.  One of them is Discord.  Still investigating what can be used as an indicator that a window is able to handle events.

UPD: 

https://github.com/qnikst/kbdd/blob/3145099e1fbbe65b27678be72465aaa5b5872874/src/libkbdd.c#L438

I've found that kbdd doesn't filter out a new window.  They only fetch the new window attributes.  We do it as well, but in the end to ensure that the new window still exists.  It feels like the checking of `WM_HINTS` and `WM_PROTOCOLS` is false positive for applications like Discord and Vivaldi which don't have `InputHint` in `WM_HINTS` and `WM_TAKE_FOCUS` in `WM_PROTOCOLS`

**Comment by ramok** [comment] 2022-09-25 09:30
> I'm sorry. I thought that had opened an issue about crashing. I've found some application which don't work as well. One of them is Discord. Still investigating what can be used as an indicator that a window is able to handle events.

Yes, I check out out, did't work with Discord

> UPD:
> 
> https://github.com/qnikst/kbdd/blob/3145099e1fbbe65b27678be72465aaa5b5872874/src/libkbdd.c#L438
> 
> I've found that kbdd doesn't filter out a new window. They only fetch the new window attributes. We do it as well, but in the end to ensure that the new window still exists. It feels like the checking of `WM_HINTS` and `WM_PROTOCOLS` is false positive for applications like Discord and Vivaldi which don't have `InputHint` in `WM_HINTS` and `WM_TAKE_FOCUS` in `WM_PROTOCOLS`

Can you provide patch?

**Comment by ANtlord** [comment] 2022-09-25 18:04
[Easy](https://github.com/ramok/xxkb/pull/4).  It also drops some trailing spaces, I hope it doesn't break the code style.

**Comment by ramok** [comment] 2022-10-11 01:11
fixed in #4

**Closed as completed by ramok** 2022-10-11 01:11 UTC
